Linear Algebra is branch of mathematics , which is widely used in Science and Engineering . 

Linear algebra contains different types of objects **Scalars , Vectors , Matrices and Tensors **

![](images/img1.png)

>**Scalars** : 
> 
    Scalar is single number 
    
>**Vector** : 
>
    Vector is array of numbers 
    
>**Matrices** : 
>
    A matrix is 2-Dimensional  array of numbers . 

>**Tensor** : 
>
    A Tensor is multi-dimensional array of numbers 

In [3]:
import numpy as np 

## Example for scalar 
s = 11
print("Scalar : ",s)
print("--------"*10)
# Example for vector 
# row vector 
rv = np.array([5,3,7])
print("row vector : {0} -- shape={1} dimension = {2}".format(rv,rv.shape,rv.ndim))
#column vector 
cv = np.array([[5],[1.5],[2]])
print("column vector : \n{0} \nshape={1} dimension = {2}".format(cv,cv.shape,cv.ndim))

print("--------"*10)
## Example for matrices 
A = np.array([[1,2,3],[5,6,7],[0,1,0]])
print("matrix")
print(A)
print(A.shape)
print(A.ndim)

Scalar :  11
--------------------------------------------------------------------------------
row vector : [5 3 7] -- shape=(3,) dimension = 1
column vector : 
[[5. ]
 [1.5]
 [2. ]] 
shape=(3, 1) dimension = 2
--------------------------------------------------------------------------------
matrix
[[1 2 3]
 [5 6 7]
 [0 1 0]]
(3, 3)
2


## Transposition
An important operation on matrices , vectors . The transpose of matrix is the mirror image of the matrix across the diagonal axis 

We donote Transpose of matrix **A** as ${A}^{\text{T}}$ and it defined as (${A}^{\text{T}})_{i,j} = {A}_{j,i}$

if the shape of the matrix is (m x n) after transpose it become (n x m)

In [4]:
## Tranposition 
# We can convert a row vector to column vector using transposition 
# Suppose we have a column matrix called v
v = np.array(list([i] for i in range(5)))
print(v)
print(type(v))
print(v.shape)
print(v.ndim)
# Now we can convert this column vector into a row vector 
r = v.T
print(r)
print(r.ndim)
print(r.shape)

[[0]
 [1]
 [2]
 [3]
 [4]]
<class 'numpy.ndarray'>
(5, 1)
2
[[0 1 2 3 4]]
2
(1, 5)


In [9]:
# We could apply transpose on 2-D matrix also 
# Suppose we have 4 x 4 matrix 
A = np.array([[1,2,3,4],[4,5,6,7],[10,20,5,6],[10,15,25,35]])
print(A)
print(A.ndim)
print(A.shape)
print(A.T)
print("shape of A : {0} and shape of  A.T:{1}".format(A.shape,A.T.shape))

B = np.array([[2,3,4],[5,6,7],[8,9,0],[4,5,6]])
print(B)
print(B.T)
print("shape of A : {0} and shape of  A.T:{1}".format(A.shape,A.T.shape))

[[ 1  2  3  4]
 [ 4  5  6  7]
 [10 20  5  6]
 [10 15 25 35]]
2
(4, 4)
[[ 1  4 10 10]
 [ 2  5 20 15]
 [ 3  6  5 25]
 [ 4  7  6 35]]
shape of A : (4, 4) and shape of  A.T:(4, 4)
[[2 3 4]
 [5 6 7]
 [8 9 0]
 [4 5 6]]
[[2 5 8 4]
 [3 6 9 5]
 [4 7 0 6]]
shape of A : (4, 4) and shape of  A.T:(4, 4)


In [5]:
## Transpose of Scalar 
# If we consider Scalar as a vector with only one value 
s = np.array([5])
s.T

array([5])

### Addition, Substraction and Multiplication

In [15]:
## Scalar is a number so we  could add substract just like we don it normally 
# suppose we have 2 scalar s1,s2
s1 = 10 
s2 = 15
#addition
print(s1+s2)
#substraction
print(s1-s2)
# multiplication 
print(s1*s2)

25
-5
150
[ 1  3  9 13]
[-1 -1  3  5]


In [25]:
# now we could consider a 2 row vector 
v1 = np.array([1,2,3,4])
v2 = np.array([0,1,6,9])

# Now we can add 2 row vector 
print(v1+v2)
# now we can substract vector v1 from v2 
print(v2-v1)

# Now we have a column vector 
v3 = np.array([[10],[20],[3],[5]])
print(v3)

[ 1  3  9 13]
[-1 -1  3  5]
[[10]
 [20]
 [ 3]
 [ 5]]


In [32]:
print(v1-v3.T)

# add a scalar to vector 
print(s1 + v1)
print(v2 - s1)
print(s1*v1)
print(v1/s1)

[[ -9 -18   0  -1]]
[11 12 13 14]
[-10  -9  -4  -1]
[10 20 30 40]
[0.1 0.2 0.3 0.4]


In [35]:
# consider a matrix 
A = np.array([[2,3,4],[6,8,9]])
B = np.array([[1,1,1],[5,5,5]])
print(A+B)
print(A-B)

[[ 3  4  5]
 [11 13 14]]
[[1 2 3]
 [1 3 4]]


In [37]:
print(A*B)
# this will perform element wise mulitiplication

[[ 2  3  4]
 [30 40 45]]


$$
\begin{bmatrix}
    A_{1,1} & A_{1,2} & A_{1,3}\\\\
    A_{2,1} & A_{2,2} & A_{2,3}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} & B_{1,2} & B_{1,3}\\\\
    B_{2,1} & B_{2,2} & B_{2,3}
\end{bmatrix}=
\begin{bmatrix}
    A_{1,1} x B_{1,1} & A_{1,2} x B_{1,2} & A_{1,3} x B_{1,3} \\\\
    A_{2,1} x B_{2,1} & A_{2,2} x B_{2,2} & A_{2,3} x B_{2,3}
\end{bmatrix}
$$

** Matrix Multiplication **

The matrix product of matrices A and B is a third matrix C. In order for this product to be defined, A must have the same number of columns as  B has rows. If A is of shape m × n and B is of shape n × p , then C is of shape
m × p . We can write the matrix product just by placing two or more matrices together, e.g.

C = AB 
      
${C}_{i,j}  =  \sum\limits_{k} {A}_{i,k} {B}_{k,j} $

- Standard product of two matrices is not just a matrix containing the product of the individual elements

In [41]:
np.dot(A,B) 
# to perform matrix multiplication 
# becoz we can not multiply a (2,3) matrix with another (2,3) matrix 
# suppose Matrix A dimension is mxn and B is dimension is nxp
# to multiply two matrix the condition is : number of columns of A == number of rows of B
# and the dimension of output will be mxp

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [40]:
# now we transpose matrix B
# and then perform the multiplication 
# so when we transpose matrix B its shape becomes 2 x 3 from (3 x 2)
# So now the condition is satisfied 
# now we can perform multiplication
C = np.dot(A,B.T)
# we are multiplying ( 2 x 3 ) matrix with ( 3 x 2) matrix 
# so the output dimension will be ( 2 x 2)
print(C)
print(C.shape)

[[  9  45]
 [ 23 115]]
(2, 2)
