Linear Algebra is branch of mathematics , which is widely used in Science and Engineering . 

Linear algebra contains different types of objects **Scalars , Vectors , Matrices and Tensors **

![](images/img1.png)

>**Scalars** : 
> 
    Scalar is single number 
    
>**Vector** : 
>
    Vector is array of numbers 
    
>**Matrices** : 
>
    A matrix is 2-Dimensional  array of numbers . 

>**Tensor** : 
>
    A Tensor is multi-dimensional array of numbers 

In [24]:
import numpy as np 

## Example for scalar 
s = 11
print("Scalar : ",s)
print("--------"*10)
# Example for vector 
# row vector 
rv = np.array([5,3,7])
print("row vector : {0} -- shape={1} dimension = {2}".format(rv,rv.shape,rv.ndim))
#column vector 
cv = np.array([[5],[1.5],[2]])
print("column vector : \n{0} \nshape={1} dimension = {2}".format(cv,cv.shape,cv.ndim))

print("--------"*10)
## Example for matrices 
A = np.array([[1,2,3],[5,6,7],[0,1,0]])
print("matrix")
print(A)
print(A.shape)
print(A.ndim)

Scalar :  11
--------------------------------------------------------------------------------
row vector : [5 3 7] -- shape=(3,) dimension = 1
column vector : 
[[5. ]
 [1.5]
 [2. ]] 
shape=(3, 1) dimension = 2
--------------------------------------------------------------------------------
matrix
[[1 2 3]
 [5 6 7]
 [0 1 0]]
(3, 3)
2


In [33]:
## Tranposition 
# We can convert a row vector to column vector using transposition 
# Suppose we have a column matrix called v
v = np.array(list([i] for i in range(5)))
print(v)
print(type(v))
print(v.shape)
print(v.ndim)
# Now we can convert this column vector into a row vector 
r = v.T
print(r)
print(r.ndim)
print(r.shape)

[[0]
 [1]
 [2]
 [3]
 [4]]
<class 'numpy.ndarray'>
(5, 1)
2
[[0 1 2 3 4]]
2
(1, 5)


In [38]:
# We could apply transpose on 2-D matrix also 
# Suppose we have 4 x 4 matrix 
A = np.array([[1,2,3,4],[4,5,6,7],[10,20,5,6],[10,15,25,35]])
print(A)
print(A.ndim)
print(A.shape)
print(A.T)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [10 20  5  6]
 [10 15 25 35]]
2
(4, 4)
[[ 1  4 10 10]
 [ 2  5 20 15]
 [ 3  6  5 25]
 [ 4  7  6 35]]
