# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [41]:
# Import NumPy as its abbreviation 'np'
import numpy as np 

In [42]:
# Create a 1-dimensional NumPy array using np.array()

array1d = np.array([1,2,3])
print(array1d)

# Create a 2-dimensional NumPy array using np.array()
array2d = np.array([[2,4,6],[3,4,5]])
print(array2d)

# Create a 3-dimensional Numpy array using np.array()
array3d = np.array([ [[1,2,3],[3,4,5]] , [[10,20,40],[5,8,9]]])
print(array3d)

array4d = np.array([ # 1st level Array (Outer)
    [ # 2nd level Array
        [[1, 2], [3, 4]], # 3rd level arrays, containing 2 4th level arrays
        [[5, 6], [7, 8]],
        [[1, 1], [0, 0]]
    ], 
    [ # 2nd Level array
        [[9, 10], [11, 12]], 
        [[13, 14], [15, 16]],
        [[11, 11],[12, 12]]
    ]
])

[1 2 3]
[[2 4 6]
 [3 4 5]]
[[[ 1  2  3]
  [ 3  4  5]]

 [[10 20 40]
  [ 5  8  9]]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [43]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print("array dimension :",array1d.ndim)
print("datatype of 1d array :",array1d.dtype)
print("size of the 1d array :",array1d.size)
print("shape of the array:",array1d.shape)


array dimension : 1
datatype of 1d array : int64
size of the 1d array : 3
shape of the array: (3,)


In [44]:
# Attributes of 2-dimensional array
print("array dimension :",array2d.ndim)
print("datatype of 1d array :",array2d.dtype)
print("size of the 1d array :",array2d.size)
print("shape of the array:",array2d.shape)


array dimension : 2
datatype of 1d array : int64
size of the 1d array : 6
shape of the array: (2, 3)


In [45]:
# Attributes of 3-dimensional array
print("array dimension :",array3d.ndim)
print("datatype of 1d array :",array3d.dtype)
print("size of the 1d array :",array3d.size)
print("shape of the array:",array3d.shape)

print("dimension :",array4d.ndim)
print("shape : ",array4d.shape)

array dimension : 3
datatype of 1d array : int64
size of the 1d array : 12
shape of the array: (2, 2, 3)
dimension : 4
shape :  (2, 3, 2, 2)


In [46]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd 
df = pd.DataFrame(array2d)
df

0  1  2
0  2  4  6
1  3  4  5

In [47]:
# Create an array of shape (10, 2) with only ones
ones_array  = np.ones((10,2))
print(ones_array)
print("\nshape:",ones_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

shape: (10, 2)


In [48]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array = np.zeros((7,2,3))
print(zeros_array)
print("\nshape:{0}\ndimension:{1}".format(zeros_array.shape,zeros_array.ndim))

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]

shape:(7, 2, 3)
dimension:3


In [49]:
# Create an array within a range of 0 and 100 with step 3
array = np.arange(0,100,3)
print(array)
print("size:",array.size)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]
size: 34


In [50]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array = np.random.randint(low=0,high=10,size=(7,2))
print(array)
array.shape

[[9 1]
 [9 3]
 [7 6]
 [8 7]
 [4 1]
 [4 7]
 [9 8]]


(7, 2)

In [51]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
array = np.random.random((3,5))
print(array)
print(array.dtype)
print(array.shape)

[[0.28093451 0.54269608 0.14092422 0.80219698 0.07455064]
 [0.98688694 0.77224477 0.19871568 0.00552212 0.81546143]
 [0.70685734 0.72900717 0.77127035 0.07404465 0.35846573]]
float64
(3, 5)


In [52]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
array = np.random.randint(low=0 ,high=10,size=(4,6))
array

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [53]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

array = np.random.randint(low=1,high=10,size=(3,7))

# Find the unique numbers in the array you just created
np.unique(array)

array([1, 2, 3, 4, 5, 7, 9])

In [54]:
# Find the 0'th index of the latest array you created
array[0]

array([9, 1, 3, 7, 4, 9, 3])

In [55]:
# Get the first 2 rows of latest array you created
array[0:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [56]:
print(array.shape)
# Get the first 2 values of the first 2 rows of the latest array
array[:2,:2]

(3, 7)


array([[9, 1],
       [5, 3]])

In [57]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
array1 = np.random.randint(low=0 , high=10 , size=(3,5))
array2 = np.ones((3,5))
print(array1)
print(array2) 

[[6 7 2 0 3]
 [1 7 3 1 5]
 [5 9 3 5 1]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [58]:
# Add the two arrays together
array1 + array2

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [59]:
# Create another array of ones of shape (5, 3)
array3 = np.ones((5,3))
array3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
# Try add the array of ones and the other most recent array together
array1 + array3
# Error becoz shape is not equal 

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [61]:
# Create another array of ones of shape (3, 5)
array4 = np.ones((3,5))
array4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
# Subtract the new array of ones from the other most recent array
array1 - array4

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [63]:
# Multiply the ones array with the latest array
array1 * array2

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [64]:
# Take the latest array to the power of 2 using '**'
array1**2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [65]:
# Do the same thing with np.square()
np.square(array1)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [66]:
# Find the mean of the latest array using np.mean()
np.mean(array1)

3.8666666666666667

In [67]:
# Find the maximum of the latest array using np.max()
np.max(array1)

9

In [68]:
# Find the minimum of the latest array using np.min()
np.min(array1)

0

In [69]:
# Find the standard deviation of the latest array
np.std(array1)

2.578543947441829

In [70]:
# Find the variance of the latest array
np.var(array1)

6.648888888888889

In [71]:
# Reshape the latest array to (3, 5, 1)
array1.reshape(3,5,1)

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [72]:
# Transpose the latest array
array1.transpose()

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

What does the transpose do?

In [73]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a1 = np.random.randint(low=0,high=10,size=(3,3))
a2 = np.random.randint(low=0,high=10,size=(3,2))
print(a1)
print(a2)

[[9 1 9]
 [3 7 6]
 [8 7 4]]
[[1 4]
 [7 9]
 [8 8]]


In [74]:
# Perform a dot product on the two newest arrays you created
np.dot(a1,a2)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [75]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a1 = np.random.randint(low=0,high=10,size=(4,3))
a2 = np.random.randint(low=0,high=10,size=(4,3))
print(a1)
print(a2)

[[0 8 6]
 [8 7 0]
 [7 7 2]
 [0 7 2]]
[[2 0 4]
 [9 6 9]
 [8 6 8]
 [7 1 0]]


In [77]:
# Perform a dot product on the two newest arrays you created
np.dot(a1,a2)
#Error becoz shape is not correct 


ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [78]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(a1.transpose(),a2)
#np.dot(a1,a2.transpose())

array([[128,  90, 128],
       [184,  91, 151],
       [ 42,  14,  40]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [79]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a1 = np.random.randint(0,10,size=(3,4))
a2 = np.random.randint(0,10,size=(3,4))
print(a1)
print(a2)


[[6 6 7 4]
 [2 7 5 2]
 [0 2 4 2]]
[[0 4 9 6]
 [6 8 9 9]
 [2 6 0 3]]


In [80]:
# Compare the two arrays with '>'
a1 > a2

array([[ True,  True, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

What happens when you compare the arrays with `>`?

In [81]:
# Compare the two arrays with '>='
a1 >= a2

array([[ True,  True, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [92]:
# Find which elements of the first array are greater than 7
a1 > 7

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [93]:
# Which parts of each array are equal? (try using '==')
a1 == a2 

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [94]:
# Sort one of the arrays you just created in ascending order
np.sort(a1)

array([[4, 6, 6, 7],
       [2, 2, 5, 7],
       [0, 2, 2, 4]])

In [95]:
# Sort the indexes of one of the arrays you just created
np.argsort(a2)

array([[0, 1, 3, 2],
       [0, 1, 2, 3],
       [2, 0, 3, 1]])

In [97]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a1)

2

In [98]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a2)

0

In [100]:
# Find the indexes with the maximum values down the verticial axis
# of one of the arrays you created
print(a1)
np.argmax(a1,axis=1)

[[6 6 7 4]
 [2 7 5 2]
 [0 2 4 2]]


array([2, 1, 2])

In [101]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created
np.argmax(a1,axis=0)

array([0, 1, 0, 0])

In [102]:
# Create an array of normally distributed random numbers
np.random.randn(3,5)

array([[ 1.79428084,  0.58068954,  0.29765045, -1.02811577, -1.41859646],
       [ 0.19033698,  0.13575383,  0.60808966,  0.70498131,  0.36092338],
       [-1.46696789,  0.89262947, -0.10525713, -0.95534644, -0.41476463]])

In [103]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.