In [1]:
# Numpy is Numerical Python 
# its one of the powerful numerical library 
# there is no array or matrix kinds of structure no in python
# But using numpy we can have those features 

In [2]:
# First import nmpy package 
import numpy as np

In [3]:
# create a simple array 
np.array([1,2,3]) 
# syntax is something like 
# np.array(python-list)
# Suppose we have list 
a = [10,20,30]
# Now we can convert into an array 
array = np.array(a)
print('list - {0} - {1}\narray - {2} - {3}'.format(a,type(a),array,type(array)))
# Now we can see the difference in the datatype 

list - [10, 20, 30] - <class 'list'>
array - [10 20 30] - <class 'numpy.ndarray'>


In [4]:
np.array([2,4,5.0])
# one element is float and other two is int 
# so all the element converted into float . 
# this is called upcast  

array([2., 4., 5.])

In [5]:
# one dimensional array 
a1 = np.array([1,2,3])
# two dimension array 
a2 = np.array([[1,2,3],[5,6,7]])

In [6]:
print(a1)
print(a1.ndim)

print(a2)
print(a2.ndim)

[1 2 3]
1
[[1 2 3]
 [5 6 7]]
2


In [7]:
a2 = np.array([1,2,3],ndmin=2)
a2

array([[1, 2, 3]])

In [8]:
print(a2.ndim)

2


In [9]:
# Now we can create numpy array with complex number 
np.array([1,5,6],dtype=complex)
# here no imaginary part thats why imaginary part is zero 

array([1.+0.j, 5.+0.j, 6.+0.j])

In [10]:
np.array([ 1,2,3,4+2j ])
# here first 3 elements in integer but the last element of array 
# is a complex number so alll other element converted into 
# complex number with imaginary part as zero 
# (upcasting)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+2.j])

In [11]:
# Data type consisting more than one element 
x = np.array( [(1,2),(3,4) ] , dtype=[('a','<i4'),('b','<i8')] )
# here the mapping is like 

# i2 - 16 bit int 
# i4 - 32 bit int 
# i8 - 64bit int
x

array([(1, 2), (3, 4)], dtype=[('a', '<i4'), ('b', '<i8')])

In [12]:
print(x['a'])
print(type(x['a'][0])) # we set type of a as int32 bit 

[1 3]
<class 'numpy.int32'>


In [13]:
print(x['b'])
print(type(x['b'][0]))

[2 4]
<class 'numpy.int64'>


In [14]:
# Numpy matrix 
# The mat() function is used to interpret a given input as a matrix.
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [15]:
np.mat([[1,2],[3,4]])

matrix([[1, 2],
        [3, 4]])

In [16]:
# the main difference between numpy array and matrix is 
# numpy matrix is 2 -dimensional 
# while numpy are N-dimensional
m = np.mat('1 2;3 4')
print(m)
print(type(m))
print(m.dtype)
print(m.ndim)

# convert the matrix into 3-Dimensional array 
array = np.array(m,ndmin=3)
print(array)
print(type(array))
print(array.dtype)
print(array.ndim)

[[1 2]
 [3 4]]
<class 'numpy.matrix'>
int64
2
[[[1 2]
  [3 4]]]
<class 'numpy.ndarray'>
int64
3


In [30]:
a = np.mat([[1,2],[7,8]])
print(type(a))
#convert  this into array using np.asarray
b = np.asarray(a)
print(type(b))
print(b)
print(b.ndim)
print(id(b))

<class 'numpy.matrix'>
<class 'numpy.ndarray'>
[[1 2]
 [7 8]]
2
140232996924032


In [35]:
# convert a list into array 
a = [1,2]

In [36]:
np.asarray(a)

array([1, 2])

In [37]:
a = np.array([1,2])
a

array([1, 2])

In [38]:
np.asarray(a) is a 

True